CREATE DATABASE IF NOT EXISTS arogya_ai;

USE arogya_ai;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(64) NOT NULL,
  created_at VARCHAR(40) NOT NULL
);
